# use java support.
language: java
jdk:
  - oraclejdk8

# install the newest java.
addons:
  apt:
    packages:
      - oracle-java8-installer

# run in container.
sudo: false

# use linux as operating system.
os:
  - linux

# configure xvfb screen.
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# skip install stage.
install: true

# run maven build.
script:
  - mvn test

