# use java support.
language: java
jdk:
  - oraclejdk8

# use operating systems.
os:
  - linux

# run in container.
sudo: false

# skip install stage.
install: true

# run maven build.
script:
  - mvn test
